import { createSlice } from '@reduxjs/toolkit'

import imgAlex36 from '../assets/users/Alex 36.webp'
import imgAlex55 from '../assets/users/Alex 55.webp'
import imgAlfredo52 from '../assets/users/Alfredo 52.webp'
import imgAlla22 from '../assets/users/Alla 22.webp'
import imgAnjella27 from '../assets/users/Anjella 27.webp'
import imgAnna38 from '../assets/users/Anna 38.webp'
import imgAntonio65 from '../assets/users/Antonio 65.webp'
import imgArtem33 from '../assets/users/Artem 33.webp'
import imgBruno33 from '../assets/users/Bruno 33.webp'
import imgCaetano63 from '../assets/users/Caetano 63.webp'
import imgCarlos48 from '../assets/users/Carlos 48.webp'
import imgDaniel40 from '../assets/users/Daniel 40.webp'
import imgDarina34 from '../assets/users/Darina 34.webp'
import imgDarina41 from '../assets/users/Darina 41.webp'
import imgDasha33 from '../assets/users/Dasha 33.webp'
import imgDebra31 from '../assets/users/Debra 31.webp'
import imgDenis43 from '../assets/users/Denis 43.webp'
import imgDmitro38 from '../assets/users/Dmitro 38.webp'
import imgElla25 from '../assets/users/Ella 25.webp'
import imgElla27 from '../assets/users/Ella 27.webp'
import imgElleonora31 from '../assets/users/Elleonora 31.webp'
import imgEvgen34 from '../assets/users/Evgen 34.webp'
import imgFabio35 from '../assets/users/Fabio 35.webp'
import imgFatima30 from '../assets/users/Fatima 30.webp'
import imgGustavo42 from '../assets/users/Gustavo 42.webp'
import imgHenrique38 from '../assets/users/Henrique 38.webp'
import imgIrina23 from '../assets/users/Irina 23.webp'
import imgJessica31 from '../assets/users/Jessica 31.webp'
import imgJose60 from '../assets/users/Jose 60.webp'
import imgJulia31 from '../assets/users/Julia 31.webp'
import imgJulio54 from '../assets/users/Julio 54.webp'
import imgJulio56 from '../assets/users/Julio 56.webp'
import imgJullia24 from '../assets/users/Jullia 24.webp'
import imgKamila45 from '../assets/users/Kamila 45.webp'
import imgKarina37 from '../assets/users/Karina 37.webp'
import imgKaya35 from '../assets/users/Kaya 35.webp'
import imgLesya25 from '../assets/users/Lesya 25.webp'
import imgLeyla24 from '../assets/users/Leyla 24.webp'
import imgLucas32 from '../assets/users/Lucas 32.webp'
import imgLuiz57 from '../assets/users/Luiz 57.webp'
import imgMartin43 from '../assets/users/Martin 43.webp'
import imgMiguel57 from '../assets/users/Miguel 57.webp'
import imgMiguel61 from '../assets/users/Miguel 61.webp'
import imgNatalia24 from '../assets/users/Natalia 24.webp'
import imgNatasha34 from '../assets/users/Natasha 34.webp'
import imgOksana37 from '../assets/users/Oksana 37.webp'
import imgOlya35 from '../assets/users/Olya 35.webp'
import imgPavlo46 from '../assets/users/Pavlo 46.webp'
import imgQuoc35 from '../assets/users/Quoc 35.webp'
import imgRachel29 from '../assets/users/Rachel 29.webp'
import imgRebecca35 from '../assets/users/Rebecca 35.webp'
import imgRicardo59 from '../assets/users/Ricardo 59.webp'
import imgRonaldo45 from '../assets/users/Ronaldo 45.webp'
import imgSergii59 from '../assets/users/Sergii 59.webp'
import imgSofia27 from '../assets/users/Sofia 27.webp'
import imgSolomiia36 from '../assets/users/Solomiia 36.webp'
import imgSweety24 from '../assets/users/Sweety 24.webp'
import imgTeresa25 from '../assets/users/Teresa 25.webp'
import imgUrsula41 from '../assets/users/Ursula 41.webp'
import imgValera32 from '../assets/users/Valera 32.webp'
import imgWando42 from '../assets/users/Wando 42.webp'
import imgWilson69 from '../assets/users/Wilson 69.webp'

const storeSlice = createSlice({
    name: 'store',
    initialState: {

        users: [
            {
                id: 1001,
                name: 'Alex',
                age: 36,
                gender: 'Male',
                city: 'Kyiv',
                country: 'Ukraine',
                height: 182,
                lookingFor: 'Relationship',
                bio: 'Full-stack developer who loves hiking and coffee. Looking for someone to explore the world with.',
                interests: ['Hiking', 'Technology', 'Coffee', 'Travel', 'Gaming'],
                avatar: imgAlex36,
                photos: [],
            },
            {
                id: 1002,
                name: 'Alex',
                age: 55,
                gender: 'Male',
                city: 'London',
                country: 'UK',
                height: 178,
                lookingFor: 'Relationship',
                bio: 'Architect with a passion for jazz and fine dining. Two grown kids. Life is great, looking for someone to share it with.',
                interests: ['Jazz', 'Architecture', 'Cooking', 'Wine', 'Travel'],
                avatar: imgAlex55,
                photos: [],
            },
            {
                id: 1003,
                name: 'Alfredo',
                age: 52,
                gender: 'Male',
                city: 'São Paulo',
                country: 'Brazil',
                height: 175,
                lookingFor: 'Friendship',
                bio: 'Chef and restaurant owner. Food is my art. I cook traditional Italian dishes with a Brazilian twist.',
                interests: ['Cooking', 'Wine', 'Football', 'Cinema', 'Travel'],
                avatar: imgAlfredo52,
                photos: [],
            },
            {
                id: 1004,
                name: 'Alla',
                age: 22,
                gender: 'Female',
                city: 'Lviv',
                country: 'Ukraine',
                height: 165,
                lookingFor: 'Relationship',
                bio: 'University student studying foreign languages. Dream of seeing Paris and Tokyo. Love books, cats, and cozy evenings.',
                interests: ['Reading', 'Languages', 'Yoga', 'Music', 'Photography'],
                avatar: imgAlla22,
                photos: [],
            },
            {
                id: 1005,
                name: 'Anjella',
                age: 27,
                gender: 'Female',
                city: 'Kyiv',
                country: 'Ukraine',
                height: 168,
                lookingFor: 'Relationship',
                bio: 'UI/UX designer obsessed with aesthetics and creativity. Spending weekends at art galleries or painting.',
                interests: ['Art', 'Design', 'Photography', 'Coffee', 'Travel'],
                avatar: imgAnjella27,
                photos: [],
            },
            {
                id: 1006,
                name: 'Anna',
                age: 38,
                gender: 'Female',
                city: 'Kyiv',
                country: 'Ukraine',
                height: 167,
                lookingFor: 'Relationship',
                bio: 'Pediatric doctor, mom of one amazing daughter. Passionate about medicine and long walks in the park.',
                interests: ['Medicine', 'Hiking', 'Reading', 'Yoga', 'Cinema'],
                avatar: imgAnna38,
                photos: [],
            },
            {
                id: 1007,
                name: 'Antonio',
                age: 65,
                gender: 'Male',
                city: 'Barcelona',
                country: 'Spain',
                height: 173,
                lookingFor: 'Friendship',
                bio: 'Retired civil engineer. Grandpa of three. I love fishing, football on Sundays, and cooking paella for the whole family.',
                interests: ['Fishing', 'Football', 'Cooking', 'Travel', 'Wine'],
                avatar: imgAntonio65,
                photos: [],
            },
            {
                id: 1008,
                name: 'Artem',
                age: 33,
                gender: 'Male',
                city: 'Kharkiv',
                country: 'Ukraine',
                height: 185,
                lookingFor: 'Relationship',
                bio: 'Mechanical engineer by day, gym enthusiast by night. I value honesty and a good sense of humor.',
                interests: ['Gym', 'Cars', 'Football', 'Gaming', 'Music'],
                avatar: imgArtem33,
                photos: [],
            },
            {
                id: 1009,
                name: 'Bruno',
                age: 33,
                gender: 'Male',
                city: 'São Paulo',
                country: 'Brazil',
                height: 180,
                lookingFor: 'Relationship',
                bio: 'Marketing manager and weekend surfer. I believe life is better with good music and good company.',
                interests: ['Surfing', 'Music', 'Travel', 'Photography', 'Cinema'],
                avatar: imgBruno33,
                photos: [],
            },
            {
                id: 1010,
                name: 'Caetano',
                age: 63,
                gender: 'Male',
                city: 'Salvador',
                country: 'Brazil',
                height: 170,
                lookingFor: 'Friendship',
                bio: 'Musician and music teacher for 35 years. Axé and samba run through my veins. Looking for genuine connection.',
                interests: ['Music', 'Dancing', 'Cooking', 'Football', 'Travel'],
                avatar: imgCaetano63,
                photos: [],
            },
            {
                id: 1011,
                name: 'Carlos',
                age: 48,
                gender: 'Male',
                city: 'Rio de Janeiro',
                country: 'Brazil',
                height: 177,
                lookingFor: 'Relationship',
                bio: 'Business consultant and football fan. I know every good restaurant in Rio. Love the ocean and Brazilian culture.',
                interests: ['Football', 'Cooking', 'Travel', 'Music', 'Cinema'],
                avatar: imgCarlos48,
                photos: [],
            },
            {
                id: 1012,
                name: 'Daniel',
                age: 40,
                gender: 'Male',
                city: 'New York',
                country: 'USA',
                height: 183,
                lookingFor: 'Relationship',
                bio: 'Corporate lawyer who unwinds by running marathons and cooking Italian food. Looking for a real partner, not just company.',
                interests: ['Running', 'Cooking', 'Reading', 'Travel', 'Wine'],
                avatar: imgDaniel40,
                photos: [],
            },
            {
                id: 1013,
                name: 'Darina',
                age: 34,
                gender: 'Female',
                city: 'Kyiv',
                country: 'Ukraine',
                height: 166,
                lookingFor: 'Relationship',
                bio: 'School teacher and amateur dancer. Children are my superpower. I love salsa, sunsets, and spontaneous road trips.',
                interests: ['Dancing', 'Travel', 'Cooking', 'Yoga', 'Cinema'],
                avatar: imgDarina34,
                photos: [],
            },
            {
                id: 1014,
                name: 'Darina',
                age: 41,
                gender: 'Female',
                city: 'Lviv',
                country: 'Ukraine',
                height: 163,
                lookingFor: 'Relationship',
                bio: 'Marketing manager and cat mom. I value quality time over quantity. Let\'s grab coffee and see where it goes.',
                interests: ['Coffee', 'Reading', 'Yoga', 'Travel', 'Art'],
                avatar: imgDarina41,
                photos: [],
            },
            {
                id: 1015,
                name: 'Dasha',
                age: 33,
                gender: 'Female',
                city: 'Odessa',
                country: 'Ukraine',
                height: 169,
                lookingFor: 'Relationship',
                bio: 'Photographer and sea lover. My camera goes everywhere with me. Always looking for the next beautiful moment.',
                interests: ['Photography', 'Travel', 'Art', 'Coffee', 'Yoga'],
                avatar: imgDasha33,
                photos: [],
            },
            {
                id: 1016,
                name: 'Debra',
                age: 31,
                gender: 'Female',
                city: 'Los Angeles',
                country: 'USA',
                height: 170,
                lookingFor: 'Relationship',
                bio: 'Actress and fitness enthusiast. LA sunshine is my fuel. Looking for someone real in a city full of illusions.',
                interests: ['Fitness', 'Dancing', 'Cinema', 'Travel', 'Fashion'],
                avatar: imgDebra31,
                photos: [],
            },
            {
                id: 1017,
                name: 'Denis',
                age: 43,
                gender: 'Male',
                city: 'Dnipro',
                country: 'Ukraine',
                height: 179,
                lookingFor: 'Relationship',
                bio: 'Construction business owner. Two kids, joint custody. I know what matters in life. Looking for a meaningful bond.',
                interests: ['Cars', 'Fishing', 'Football', 'Gym', 'Hiking'],
                avatar: imgDenis43,
                photos: [],
            },
            {
                id: 1018,
                name: 'Dmitro',
                age: 38,
                gender: 'Male',
                city: 'Kyiv',
                country: 'Ukraine',
                height: 181,
                lookingFor: 'Relationship',
                bio: 'Backend developer at a fintech startup. I code by day and read sci-fi by night. Looking for my favorite person.',
                interests: ['Technology', 'Reading', 'Gaming', 'Coffee', 'Hiking'],
                avatar: imgDmitro38,
                photos: [],
            },
            {
                id: 1019,
                name: 'Ella',
                age: 25,
                gender: 'Female',
                city: 'Kyiv',
                country: 'Ukraine',
                height: 172,
                lookingFor: 'Relationship',
                bio: 'Model and aspiring actress. Life is a runway — dress accordingly. Love art, good food, and late-night conversations.',
                interests: ['Fashion', 'Art', 'Dancing', 'Travel', 'Cinema'],
                avatar: imgElla25,
                photos: [],
            },
            {
                id: 1020,
                name: 'Ella',
                age: 27,
                gender: 'Female',
                city: 'Berlin',
                country: 'Germany',
                height: 167,
                lookingFor: 'Friendship',
                bio: 'Visual artist and gallery curator. Berlin\'s creative chaos is my home. Let\'s discuss art over a glass of wine.',
                interests: ['Art', 'Music', 'Photography', 'Reading', 'Wine'],
                avatar: imgElla27,
                photos: [],
            },
            {
                id: 1021,
                name: 'Elleonora',
                age: 31,
                gender: 'Female',
                city: 'Rome',
                country: 'Italy',
                height: 171,
                lookingFor: 'Relationship',
                bio: 'Fashion stylist born and raised in Rome. Espresso, fashion weeks, and Sunday markets are my religion.',
                interests: ['Fashion', 'Art', 'Cooking', 'Travel', 'Cinema'],
                avatar: imgElleonora31,
                photos: [],
            },
            {
                id: 1022,
                name: 'Evgen',
                age: 34,
                gender: 'Male',
                city: 'Zaporizhzhia',
                country: 'Ukraine',
                height: 184,
                lookingFor: 'Relationship',
                bio: 'Welding engineer and amateur boxer. Straight-forward and loyal. Looking for someone who values sincerity.',
                interests: ['Boxing', 'Gym', 'Cars', 'Football', 'Camping'],
                avatar: imgEvgen34,
                photos: [],
            },
            {
                id: 1023,
                name: 'Fabio',
                age: 35,
                gender: 'Male',
                city: 'Rio de Janeiro',
                country: 'Brazil',
                height: 183,
                lookingFor: 'Relationship',
                bio: 'Personal trainer and beach volleyball player. The ocean is my second home. Passion for life is my best feature.',
                interests: ['Fitness', 'Volleyball', 'Surfing', 'Cooking', 'Travel'],
                avatar: imgFabio35,
                photos: [],
            },
            {
                id: 1024,
                name: 'Fatima',
                age: 30,
                gender: 'Female',
                city: 'Istanbul',
                country: 'Turkey',
                height: 164,
                lookingFor: 'Relationship',
                bio: 'Entrepreneur and travel blogger. I have visited 32 countries. Looking for someone adventurous enough to keep up.',
                interests: ['Travel', 'Photography', 'Cooking', 'Fashion', 'Languages'],
                avatar: imgFatima30,
                photos: [],
            },
            {
                id: 1025,
                name: 'Gustavo',
                age: 42,
                gender: 'Male',
                city: 'São Paulo',
                country: 'Brazil',
                height: 180,
                lookingFor: 'Relationship',
                bio: 'CEO of a tech company. Busy life but always time for the right person. Passionate about business, music, and travel.',
                interests: ['Travel', 'Music', 'Golf', 'Wine', 'Reading'],
                avatar: imgGustavo42,
                photos: [],
            },
            {
                id: 1026,
                name: 'Henrique',
                age: 38,
                gender: 'Male',
                city: 'Curitiba',
                country: 'Brazil',
                height: 179,
                lookingFor: 'Relationship',
                bio: 'Architect and cycling enthusiast. I designed my own house and cook better than most restaurants. Let\'s talk over dinner.',
                interests: ['Cycling', 'Cooking', 'Architecture', 'Travel', 'Music'],
                avatar: imgHenrique38,
                photos: [],
            },
            {
                id: 1027,
                name: 'Irina',
                age: 23,
                gender: 'Female',
                city: 'Kyiv',
                country: 'Ukraine',
                height: 166,
                lookingFor: 'Relationship',
                bio: 'Psychology student and bookworm. I analyze people for a hobby — don\'t worry, I\'m nice about it. Love coffee and deep talks.',
                interests: ['Reading', 'Psychology', 'Coffee', 'Yoga', 'Music'],
                avatar: imgIrina23,
                photos: [],
            },
            {
                id: 1028,
                name: 'Jessica',
                age: 31,
                gender: 'Female',
                city: 'Miami',
                country: 'USA',
                height: 169,
                lookingFor: 'Relationship',
                bio: 'Lifestyle influencer and yoga instructor. Sun, sea, and smoothies. Looking for someone genuine beyond the filters.',
                interests: ['Yoga', 'Fitness', 'Travel', 'Dancing', 'Photography'],
                avatar: imgJessica31,
                photos: [],
            },
            {
                id: 1029,
                name: 'Jose',
                age: 60,
                gender: 'Male',
                city: 'Lisbon',
                country: 'Portugal',
                height: 171,
                lookingFor: 'Friendship',
                bio: 'Retired fisherman turned olive oil producer. I know the best fishing spots and the best wine in the Alentejo.',
                interests: ['Fishing', 'Cooking', 'Wine', 'Football', 'Travel'],
                avatar: imgJose60,
                photos: [],
            },
            {
                id: 1030,
                name: 'Julia',
                age: 31,
                gender: 'Female',
                city: 'Lviv',
                country: 'Ukraine',
                height: 170,
                lookingFor: 'Relationship',
                bio: 'Lawyer with a soft side. I fight for justice by day and bake sourdough on weekends. Looking for my equal.',
                interests: ['Reading', 'Cooking', 'Travel', 'Yoga', 'Cinema'],
                avatar: imgJulia31,
                photos: [],
            },
            {
                id: 1031,
                name: 'Julio',
                age: 54,
                gender: 'Male',
                city: 'Rio de Janeiro',
                country: 'Brazil',
                height: 176,
                lookingFor: 'Relationship',
                bio: 'Cardiologist and amateur chef. Life taught me to slow down and enjoy the small things. Great conversation starter.',
                interests: ['Cooking', 'Medicine', 'Travel', 'Music', 'Wine'],
                avatar: imgJulio54,
                photos: [],
            },
            {
                id: 1032,
                name: 'Julio',
                age: 56,
                gender: 'Male',
                city: 'São Paulo',
                country: 'Brazil',
                height: 174,
                lookingFor: 'Relationship',
                bio: 'University professor of history. I write books, drink too much coffee, and still believe in love at any age.',
                interests: ['Reading', 'History', 'Coffee', 'Cinema', 'Travel'],
                avatar: imgJulio56,
                photos: [],
            },
            {
                id: 1033,
                name: 'Jullia',
                age: 24,
                gender: 'Female',
                city: 'Florianópolis',
                country: 'Brazil',
                height: 164,
                lookingFor: 'Relationship',
                bio: 'Tourism student and beach lover. I speak three languages and can find the best açaí in any city. Let\'s explore!',
                interests: ['Travel', 'Surfing', 'Languages', 'Dancing', 'Photography'],
                avatar: imgJullia24,
                photos: [],
            },
            {
                id: 1034,
                name: 'Kamila',
                age: 45,
                gender: 'Female',
                city: 'Warsaw',
                country: 'Poland',
                height: 165,
                lookingFor: 'Relationship',
                bio: 'HR director and weekend cyclist. I\'ve organized 500 interviews but still get nervous on first dates. Ready for something real.',
                interests: ['Cycling', 'Reading', 'Wine', 'Yoga', 'Travel'],
                avatar: imgKamila45,
                photos: [],
            },
            {
                id: 1035,
                name: 'Karina',
                age: 37,
                gender: 'Female',
                city: 'Kharkiv',
                country: 'Ukraine',
                height: 162,
                lookingFor: 'Relationship',
                bio: 'Pastry chef and food blogger. My kitchen smells like heaven. Looking for someone to taste my experiments.',
                interests: ['Cooking', 'Coffee', 'Art', 'Travel', 'Fashion'],
                avatar: imgKarina37,
                photos: [],
            },
            {
                id: 1036,
                name: 'Kaya',
                age: 35,
                gender: 'Female',
                city: 'Istanbul',
                country: 'Turkey',
                height: 168,
                lookingFor: 'Relationship',
                bio: 'Interior designer with a love for minimalism. Istanbul and its chaos inspire everything I create. Let\'s share a coffee on the Bosphorus.',
                interests: ['Design', 'Art', 'Travel', 'Yoga', 'Coffee'],
                avatar: imgKaya35,
                photos: [],
            },
            {
                id: 1037,
                name: 'Lesya',
                age: 25,
                gender: 'Female',
                city: 'Lviv',
                country: 'Ukraine',
                height: 163,
                lookingFor: 'Relationship',
                bio: 'Primary school teacher who loves children\'s laughter more than anything. Autumn in Lviv, hot chocolate, and good company.',
                interests: ['Teaching', 'Reading', 'Hiking', 'Music', 'Cooking'],
                avatar: imgLesya25,
                photos: [],
            },
            {
                id: 1038,
                name: 'Leyla',
                age: 24,
                gender: 'Female',
                city: 'Baku',
                country: 'Azerbaijan',
                height: 166,
                lookingFor: 'Relationship',
                bio: 'International relations student with a passion for diplomacy and travel. I speak four languages. Curious about everything.',
                interests: ['Languages', 'Travel', 'Reading', 'Dancing', 'Music'],
                avatar: imgLeyla24,
                photos: [],
            },
            {
                id: 1039,
                name: 'Lucas',
                age: 32,
                gender: 'Male',
                city: 'São Paulo',
                country: 'Brazil',
                height: 181,
                lookingFor: 'Relationship',
                bio: 'Software developer and rock climber. I build apps that millions use and walls that only I can climb. Partner in both?',
                interests: ['Climbing', 'Technology', 'Music', 'Travel', 'Coffee'],
                avatar: imgLucas32,
                photos: [],
            },
            {
                id: 1040,
                name: 'Luiz',
                age: 57,
                gender: 'Male',
                city: 'Belo Horizonte',
                country: 'Brazil',
                height: 175,
                lookingFor: 'Relationship',
                bio: 'Civil engineer who has built bridges across Brazil. Now I want to build something more personal. Love football and grilling.',
                interests: ['Football', 'Cooking', 'Travel', 'Fishing', 'Music'],
                avatar: imgLuiz57,
                photos: [],
            },
            {
                id: 1041,
                name: 'Martin',
                age: 43,
                gender: 'Male',
                city: 'Buenos Aires',
                country: 'Argentina',
                height: 178,
                lookingFor: 'Relationship',
                bio: 'Import/export businessman and tango enthusiast. Buenos Aires is the most romantic city on earth — come visit and I\'ll prove it.',
                interests: ['Tango', 'Travel', 'Wine', 'Football', 'Cooking'],
                avatar: imgMartin43,
                photos: [],
            },
            {
                id: 1042,
                name: 'Miguel',
                age: 57,
                gender: 'Male',
                city: 'Madrid',
                country: 'Spain',
                height: 176,
                lookingFor: 'Relationship',
                bio: 'Architect and art collector. Madrid\'s museums and tapas bars are my second office. Seeking a woman with curiosity and warmth.',
                interests: ['Art', 'Architecture', 'Wine', 'Travel', 'Music'],
                avatar: imgMiguel57,
                photos: [],
            },
            {
                id: 1043,
                name: 'Miguel',
                age: 61,
                gender: 'Male',
                city: 'Lisbon',
                country: 'Portugal',
                height: 172,
                lookingFor: 'Friendship',
                bio: 'Retired navy officer turned sailing instructor. The sea is my element. I tell great stories and make even better coffee.',
                interests: ['Sailing', 'Fishing', 'Cooking', 'Travel', 'Reading'],
                avatar: imgMiguel61,
                photos: [],
            },
            {
                id: 1044,
                name: 'Natalia',
                age: 24,
                gender: 'Female',
                city: 'Kyiv',
                country: 'Ukraine',
                height: 171,
                lookingFor: 'Relationship',
                bio: 'Model and economics student. Don\'t judge a book by its cover — I\'m smarter than I look and funnier than you expect.',
                interests: ['Fashion', 'Travel', 'Dancing', 'Coffee', 'Yoga'],
                avatar: imgNatalia24,
                photos: [],
            },
            {
                id: 1045,
                name: 'Natasha',
                age: 34,
                gender: 'Female',
                city: 'Odessa',
                country: 'Ukraine',
                height: 167,
                lookingFor: 'Relationship',
                bio: 'E-commerce entrepreneur and sea swimmer. I built my business from scratch and I\'m proud of it. Looking for an equal partner.',
                interests: ['Swimming', 'Business', 'Travel', 'Cooking', 'Wine'],
                avatar: imgNatasha34,
                photos: [],
            },
            {
                id: 1046,
                name: 'Oksana',
                age: 37,
                gender: 'Female',
                city: 'Kyiv',
                country: 'Ukraine',
                height: 165,
                lookingFor: 'Relationship',
                bio: 'Project manager at an IT company. Organized chaos is my specialty. Love hiking and spontaneous weekend trips.',
                interests: ['Hiking', 'Travel', 'Yoga', 'Reading', 'Coffee'],
                avatar: imgOksana37,
                photos: [],
            },
            {
                id: 1047,
                name: 'Olya',
                age: 35,
                gender: 'Female',
                city: 'Kharkiv',
                country: 'Ukraine',
                height: 164,
                lookingFor: 'Relationship',
                bio: 'Graphic designer and illustrator. My walls are covered in art. Looking for someone who appreciates creativity and long walks.',
                interests: ['Art', 'Design', 'Music', 'Hiking', 'Cinema'],
                avatar: imgOlya35,
                photos: [],
            },
            {
                id: 1048,
                name: 'Pavlo',
                age: 46,
                gender: 'Male',
                city: 'Kyiv',
                country: 'Ukraine',
                height: 180,
                lookingFor: 'Relationship',
                bio: 'Business owner in logistics. Father of two teenagers. I love mountains, good whiskey, and honest conversations.',
                interests: ['Hiking', 'Cars', 'Football', 'Whiskey', 'Travel'],
                avatar: imgPavlo46,
                photos: [],
            },
            {
                id: 1049,
                name: 'Quoc',
                age: 35,
                gender: 'Male',
                city: 'Ho Chi Minh City',
                country: 'Vietnam',
                height: 172,
                lookingFor: 'Relationship',
                bio: 'Software engineer and street food connoisseur. Vietnam has the best food in the world — I will fight anyone who disagrees.',
                interests: ['Cooking', 'Technology', 'Travel', 'Photography', 'Gaming'],
                avatar: imgQuoc35,
                photos: [],
            },
            {
                id: 1050,
                name: 'Rachel',
                age: 29,
                gender: 'Female',
                city: 'Tel Aviv',
                country: 'Israel',
                height: 168,
                lookingFor: 'Relationship',
                bio: 'Journalist and documentary filmmaker. I ask too many questions — it\'s my job. Passionate about stories and human connection.',
                interests: ['Cinema', 'Travel', 'Photography', 'Reading', 'Coffee'],
                avatar: imgRachel29,
                photos: [],
            },
            {
                id: 1051,
                name: 'Rebecca',
                age: 35,
                gender: 'Female',
                city: 'New York',
                country: 'USA',
                height: 166,
                lookingFor: 'Relationship',
                bio: 'High school English teacher and amateur poet. I believe the right book at the right time can change your life.',
                interests: ['Reading', 'Writing', 'Coffee', 'Hiking', 'Music'],
                avatar: imgRebecca35,
                photos: [],
            },
            {
                id: 1052,
                name: 'Ricardo',
                age: 59,
                gender: 'Male',
                city: 'Porto Alegre',
                country: 'Brazil',
                height: 177,
                lookingFor: 'Relationship',
                bio: 'Orthopedic surgeon and wine enthusiast. South Brazil wine country is my favorite place. Looking for a companion for life\'s second half.',
                interests: ['Wine', 'Cooking', 'Travel', 'Golf', 'Reading'],
                avatar: imgRicardo59,
                photos: [],
            },
            {
                id: 1053,
                name: 'Ronaldo',
                age: 45,
                gender: 'Male',
                city: 'São Paulo',
                country: 'Brazil',
                height: 182,
                lookingFor: 'Relationship',
                bio: 'Football coach and ex-professional player. I live and breathe sports. Best dad trophy belongs to me though.',
                interests: ['Football', 'Gym', 'Travel', 'Cooking', 'Music'],
                avatar: imgRonaldo45,
                photos: [],
            },
            {
                id: 1054,
                name: 'Sergii',
                age: 59,
                gender: 'Male',
                city: 'Kyiv',
                country: 'Ukraine',
                height: 176,
                lookingFor: 'Relationship',
                bio: 'Retired aerospace engineer. Grandpa of two. I fix everything in the house and nothing on my phone. Seeking warmth and company.',
                interests: ['Fishing', 'Camping', 'History', 'Chess', 'Cooking'],
                avatar: imgSergii59,
                photos: [],
            },
            {
                id: 1055,
                name: 'Sofia',
                age: 27,
                gender: 'Female',
                city: 'Kyiv',
                country: 'Ukraine',
                height: 169,
                lookingFor: 'Relationship',
                bio: 'Watercolor artist and art teacher. I see the world in colors. My dream is to have a studio with a view of the mountains.',
                interests: ['Art', 'Music', 'Travel', 'Yoga', 'Photography'],
                avatar: imgSofia27,
                photos: [],
            },
            {
                id: 1056,
                name: 'Solomiia',
                age: 36,
                gender: 'Female',
                city: 'Lviv',
                country: 'Ukraine',
                height: 167,
                lookingFor: 'Relationship',
                bio: 'Violinist in the Lviv Philharmonic. Music is my mother tongue. Looking for someone who listens with their heart.',
                interests: ['Music', 'Art', 'Travel', 'Reading', 'Coffee'],
                avatar: imgSolomiia36,
                photos: [],
            },
            {
                id: 1057,
                name: 'Sweety',
                age: 24,
                gender: 'Female',
                city: 'Mumbai',
                country: 'India',
                height: 161,
                lookingFor: 'Relationship',
                bio: 'Computer science student and classical Bharatnatyam dancer. Blending tradition and modernity every single day.',
                interests: ['Dancing', 'Technology', 'Reading', 'Yoga', 'Travel'],
                avatar: imgSweety24,
                photos: [],
            },
            {
                id: 1058,
                name: 'Teresa',
                age: 25,
                gender: 'Female',
                city: 'Porto',
                country: 'Portugal',
                height: 165,
                lookingFor: 'Relationship',
                bio: 'Architecture student in love with Porto\'s azulejos and Fado music. Let\'s walk the Douro riverside together someday.',
                interests: ['Architecture', 'Music', 'Photography', 'Travel', 'Wine'],
                avatar: imgTeresa25,
                photos: [],
            },
            {
                id: 1059,
                name: 'Ursula',
                age: 41,
                gender: 'Female',
                city: 'Munich',
                country: 'Germany',
                height: 170,
                lookingFor: 'Relationship',
                bio: 'HR director at an automotive company. Precision and empathy in equal measure. Love hiking in the Bavarian Alps.',
                interests: ['Hiking', 'Reading', 'Wine', 'Yoga', 'Travel'],
                avatar: imgUrsula41,
                photos: [],
            },
            {
                id: 1060,
                name: 'Valera',
                age: 32,
                gender: 'Male',
                city: 'Dnipro',
                country: 'Ukraine',
                height: 180,
                lookingFor: 'Relationship',
                bio: 'Auto mechanic and motocross rider. I can fix any engine. Looking for someone who doesn\'t need fixing but chooses me anyway.',
                interests: ['Motocross', 'Cars', 'Gym', 'Camping', 'Football'],
                avatar: imgValera32,
                photos: [],
            },
            {
                id: 1061,
                name: 'Wando',
                age: 42,
                gender: 'Male',
                city: 'Salvador',
                country: 'Brazil',
                height: 178,
                lookingFor: 'Relationship',
                bio: 'Chef specializing in Bahian cuisine. Cooking is love made visible. Come eat my moqueca and tell me I\'m wrong.',
                interests: ['Cooking', 'Music', 'Dancing', 'Football', 'Travel'],
                avatar: imgWando42,
                photos: [],
            },
            {
                id: 1062,
                name: 'Wilson',
                age: 69,
                gender: 'Male',
                city: 'Rio de Janeiro',
                country: 'Brazil',
                height: 173,
                lookingFor: 'Friendship',
                bio: 'Retired doctor and passionate birdwatcher. Rio\'s mountains and birds are my daily meditation. Looking for good conversation and laughter.',
                interests: ['Birdwatching', 'Hiking', 'Reading', 'Cooking', 'Chess'],
                avatar: imgWilson69,
                photos: [],
            },
        ],

        filters: {
            gender: '',
            ageRange: '',
            lookingFor: '',
        },

    },
    reducers: {
        getUsers: (state, action) => {
            state.users = action.payload
        },

        setFilter: (state, action) => {
            const { name, value } = action.payload
            state.filters[name] = value
        },

        resetFilters: (state) => {
            state.filters = { gender: '', ageRange: '', lookingFor: '' }
        },
    },
})

export const { getUsers, setFilter, resetFilters } = storeSlice.actions
export default storeSlice.reducer
